# Generated by Django 3.2.6 on 2021-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('author', models.CharField(max_length=240)),
                ('isbn', models.CharField(max_length=30)),
                ('numberOfPages', models.IntegerField()),
                ('language', models.CharField(choices=[('eng', 'English'), ('de', 'German'), ('tr', 'Turkish')], default='English', max_length=40)),
                ('edition', models.IntegerField()),
                ('publisher', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
