# Generated by Django 3.2.6 on 2021-08-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
